<?php if ($error): ?>
<h3>Error Form while updating</h3>
<?php endif ?>
<h3>Create a Post</h3>

<form method="post">
	<input name="title" type="text" placeholder="Title" style="margin-bottom:15px;" /><br />
	<textarea name="detail" rows="10" cols="50" style="margin-bottom:15px;" placeholder="Content"></textarea><br />
	<input type="submit" class='btn btn-warning' value="Create" style="margin-bottom:15px;" />
</form>

	