<!-- head problem -->
<nav class="head navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">My Blog</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="header">
			<ul class="nav navbar-nav">
				<li><a href="/php-bloggy/training/user">Users</a></li>
				<li><a href="/php-bloggy/training/post">Posts</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<?php if(isset($user, $picture)): ?>
					<img width=25px src= "<?php echo $picture; ?>" >
					<li>Ohai <?php echo $user['first_name']; ?></li>
					<li><a href="/php-bloggy/training/user/logout">Logout</a></li>
				<?php else: ?>
					<li><a href="/php-bloggy/training/user/login">Login</a></li>
                <?php endif; ?>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>