<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?php echo $title; ?></title>
<link rel="stylesheet" type="text/css" href="/php-bloggy/training/assets/styles/fontawesome.css" />
<link rel="stylesheet" type="text/css" href="/php-bloggy/training/assets/styles/fonts.css" />
<link rel="stylesheet" type="text/css" href="/php-bloggy/training/assets/styles/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="/php-bloggy/training/assets/styles/application.css" />

<script type="text/javascript" src="/php-bloggy/training/assets/scripts/jquery.js"></script>
<script type="text/javascript" src="/php-bloggy/training/assets/scripts/bootstrap.js"></script>
</head>

<body>

<?php echo $head; ?>

<section class="body container">
	<?php echo $body; ?>
</section>

<?php echo $foot; ?>

</body>
</html>