<a class='btn btn-warning' href=<?php echo "./post/create"; ?> >Create Post</a>
<table class='table-bordered' cellpadding='0' cellspacing='0' width='100%' style='margin-top:15px; margin-bottom:15px;'>
	<thead>
		<td>Action</td>
		<td>User ID</td>
		<td>Post ID</td>
		<td>Title</td>
	</thead>

	<tbody>
		<?php if (empty($rows)): ?>
			<tr> 
				<td colspan="3" style=" text-align: -webkit-center; vertical-align: middle;" >
					<?php echo $emptyMessage ?></td> 
			</tr>
		<?php else: ?>
			<?php foreach($rows as $row): ?>
			<tr>
				<td> 
					<a href=<?php echo "./post/remove/" . $row['post_id'];?> class='fa fa-remove'></a>
					&nbsp;&nbsp;&nbsp;
					<a href=<?php echo "./post/update/" . $row['post_id'];?> class='fa fa-edit'></a>
					&nbsp;&nbsp;&nbsp;
					<a href=<?php echo "./post/facebook/" . $row['post_id'];?> class='fa fa-facebook-square'></a>
				</td>
				<td><?php echo $row['user_id']; ?></td>
				<td><?php echo $row['post_id']; ?></td>
				<td><?php echo $row['post_title']; ?></td>
			</tr>
			<?php endforeach; ?>
		<?php endif; ?>
	</tbody>
</table>
