<a class='btn btn-info' href=<?php echo "./post"; ?> >Posts</a>
<a class='btn btn-danger' href=<?php echo "./postfb"; ?> >Post to FB</a>
<table class='table-bordered' cellpadding='0' cellspacing='0' width='100%' style='margin-top:15px; margin-bottom:15px;'>
	<thead>
		<td>Action</td>
		<td>ID</td>
		<td>Name</td>
	</thead>

	<tbody>
		<?php foreach($rows as $row): ?>
		<tr>
			<td> 
				<a href=<?php echo "./user/remove/" . $row['user_id'];?> class='fa fa-remove'></a>
			</td>
			<td><?php echo $row['user_id']; ?></td>
			<td><?php echo $row['user_name']; ?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>	
</table>
